create database db_pizzaria_legal;

use db_pizzaria_legal;

CREATE TABLE TB_CATEGORIA(
ID BIGINT AUTO_INCREMENT NOT NULL,
TIPO VARCHAR(40) NOT NULL,
TAMANHO CHAR NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE TB_PIZZA(
ID BIGINT AUTO_INCREMENT NOT NULL,
NOME VARCHAR(50) NOT NULL,
PRECO DECIMAL(10,2) NOT NULL,
BORDA_RECHEADA CHAR NOT NULL,
OBSERVACAO VARCHAR(255),
ID_CATEGORIA BIGINT NOT NULL,

PRIMARY KEY (ID),
FOREIGN KEY (ID_CATEGORIA) REFERENCES TB_CATEGORIA(ID));


INSERT INTO TB_CATEGORIA (TIPO,TAMANHO)
VALUES
("Brotinho","P"),
("Média","M"),
("Grande","G"),
("Extra-Grande","X"),
("Individual","I");

INSERT INTO TB_PIZZA 
VALUES 
(DEFAULT,"MUSSARELA", 30.90, "N",null ,3),
(DEFAULT,"CALABREZA",30.90, "N", "SEM CEBOLA",3),
(DEFAULT,"3 QUEIJOS", 35.00, "S", null,4),
(DEFAULT,"PALMITO", 32.00, "S", null,3),
(DEFAULT,"MUSSARELA", 15.00, "N",null, 1),
(DEFAULT,"4 QUEIJOS", 40.00, "N",null, 3),
(DEFAULT,"CALABREZA", 15.00, "N","SEM CEBOLA", 1),
(DEFAULT,"FILÉ MIGNON", 50.00, "N","SEM CEBOLA", 3),
(DEFAULT,"MODA DA CASA",8.90, "N","SEM CEBOLA",5);

SELECT * FROM TB_PIZZA;
SELECT * FROM TB_CATEGORIA;

SELECT * FROM TB_PIZZA WHERE PRECO > 45;

SELECT * FROM TB_PIZZA WHERE PRECO BETWEEN 29 AND 60;

SELECT * FROM TB_PIZZA WHERE NOME LIKE 'C%';

SELECT *
FROM TB_PIZZA
INNER JOIN TB_CATEGORIA
ON TB_PIZZA.ID_CATEGORIA = TB_CATEGORIA.ID
ORDER BY TB_PIZZA.ID;

SELECT *
FROM TB_PIZZA
INNER JOIN TB_CATEGORIA
ON TB_PIZZA.ID_CATEGORIA = TB_CATEGORIA.ID
WHERE TB_CATEGORIA.TAMANHO = "G"
ORDER BY TB_PIZZA.ID;

